data:
  root_dir: artifacts/data
  source_URL: https://drive.google.com/file/d/1E2RTgqiPqoKFTjhKyhjXyGYbpH1ILzZv/view?usp=sharing
  local_data_file: artifacts/data/data.zip
  unzip_dir: artifacts
  
data_path: "artifacts/yield_df.csv"
processed_data_path: "artifacts/processed_data.csv"
model: "model/dtr.pkl"
processor: "model/processor.pkl"